# LLM Configuration
fast_llm_provider: openai   # Options: 'openai', 'google', 'anthropic'
long_context_llm_provider: openai
embeddings_model: openai

# Text-to-Speech Configuration
tts_provider: openai  # Options: 'google', 'elevenlabs', 'google_multispeaker', 'openai'

tts_settings:
  openai:
    voice_mapping:
      Interviewer: Echo
      Interviewee: nova
    model: gpt-4o-mini-tts # tts-1  tts-1-hd  gpt-4o-mini-tts
  elevenlabs:
    voice_mapping:
      Interviewer: UgBBYS2sOqTuMpoF3BR0 #Mark
      Interviewee: 56AoDkrOh6qfVPDXZ7Pt #Cassidy
    model: eleven_flash_v2_5
  google:
    voice_mapping:
      Interviewer: en-US-Journey-F
      Interviewee: en-US-Journey-D
    language_code: en-US
    effects_profile_id: small-bluetooth-speaker-class-device
  google_multispeaker:
    voice_mapping:
      Interviewer: R
      Interviewee: S
    language_code: en-US
    effects_profile_id: small-bluetooth-speaker-class-device

# Audio output settings
output_format: mp3  # Options: 'mp3', 'wav'

# Directory paths
temp_audio_dir: ./.temp_audio
output_dir: ./output
checkpoint_dir : ./.checkpoints

# Rate limiting settings
rate_limits:
  elevenlabs:
    requests_per_minute: 20
    max_retries: 10
    base_delay: 2.0
  google:
    requests_per_minute: 20
    max_retries: 10
    base_delay: 2.0


# Content settings
podcast_name: Podcast LLM

# Available variables: podcast_name, topic 
intro: "Welcome to {podcast_name}. Today we've invited an expert to talk about {topic}." 
outro: "That's all for today. Thank you for listening to {podcast_name}. See you next time when we'll talk about whatever you want."

# Episode structure
episode_structure:
  - Episode Introduction (with subsections)
  - Main Discussion Topics (with subsections)
  - Conclusion (with subsections)
